[package]
name = "xcode-renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.21.0", features = ["derive"] }
taffy = "0.7.1"
xcode-terminal = { path = "../../terminal/xcode-terminal" }
xcode-services = { path = "../../services/xcode-services" }
tree-sitter = "0.24.7"
tree-sitter-rust = "0.23.2"
env_logger = "0.11.10"
glyphon = "0.11.0"
log = "0.4.29"
pollster = "0.4.0"
wgpu = "29.0.3"
winit = "0.30.13"
xcode-core = { path = "../../core/xcode-core" }
xcode-ui = { path = "../../ui/xcode-ui" }
