[package]
name = "xcode-renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck.workspace = true
taffy.workspace = true
xcode-terminal = { path = "../../terminal/xcode-terminal" }
xcode-services = { path = "../../services/xcode-services" }
tree-sitter.workspace = true
tree-sitter-rust.workspace = true
env_logger.workspace = true
glyphon.workspace = true
log.workspace = true
pollster.workspace = true
wgpu.workspace = true
winit.workspace = true
xcode-core = { path = "../../core/xcode-core" }
xcode-ui = { path = "../../ui/xcode-ui" }
serde_json.workspace = true
